# A file for functions  of numpy library
(Note: These are all simple implementations)


In [2]:
# import numpy as np so that we can use it to create and manipulate arrays
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# Create a 2D array
matrix = np.array([[1, 2], [3, 4]])
print(matrix)


[1 2 3 4]
[[1 2]
 [3 4]]


In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)        # element-wise addition
print(a * b)        # element-wise multiplication
print(a ** 2)       # element-wise square
print(b ** 3)       # element-wise cube

[5 7 9]
[ 4 10 18]
[1 4 9]
[ 64 125 216]


3.0
3.0
1.4142135623730951
15


In [6]:



print(np.mean(arr))   # average
print(np.median(arr))
print(np.std(arr))    # standard deviation
print(np.sum(arr))    # total sum


3.5
3.5
1.707825127659933
21


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)             # (2, 3)
print(arr.reshape(3, 2))     # reshape to (3, 2)
print(arr.flatten())         # convert to 1D: [1 2 3 4 5 6]



(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.vstack((a, b)))   # vertical stack (4 rows)
print(np.hstack((a, b)))   # horizontal stack (4 columns)
print(np.concatenate((a, b), axis=0))  # same as vstack


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

# Get all elements greater than 25
print(arr[arr > 25])

# Replace values
arr[arr > 25] = 99
print(arr)


[30 40 50]
[10 20 99 99 99]


Random number generation can be done with numpy as follows

In [ ]:
np.random.seed(42)                # reproducible results

print(np.random.rand(3))          # 3 random floats [0,1)
print(np.random.randint(0, 10, 5))  # 5 random integers [0,10)

# Random normal distribution
print(np.random.normal(loc=0, scale=1, size=(2, 3))) # loc = mean, scale = std dev, size = shape of matrix


[0.37454012 0.95071431 0.73199394]
[4 6 9 2 6]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


argmax gives the index of max value in array

argmin gives the index of min value in array

In [11]:
arr = np.array([10, 20, 5, 40])
print(np.argmax(arr))  # index of max → 3
print(np.argmin(arr))  # index of min → 2


3
2


basic dot product


In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))     # matrix multiplication
print(A @ B)            # same as dot product


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


numpy can give mean, deviation and variance as follows

In [6]:
arr = np.array([197, 234, 330, 40, 500])
print("Mean =", np.mean(arr))  # mean
print("median = ", np.median(arr))  # median
print("deviation = ", np.std(arr))  # standard deviation
print("variance = ", np.var(arr))  # variance

Mean = 260.2
median =  234.0
deviation =  152.01631491389338
variance =  23108.96


getting unique labels/ classes

In [ ]:
labels = np.array([0, 1, 0, 2, 1, 1])
print(np.unique(labels))         # [0 1 2]
print(np.unique(labels, return_counts=True))  
#this funtions returns unique labels and their counts
# (array([0, 1, 2]), array([2, 3, 1])



[0 1 2]
(array([0, 1, 2]), array([2, 3, 1]))


Vector magnitude
Used in regularization, normalization, and similarity.

In [8]:
vec = np.array([3, 4])
print(np.linalg.norm(vec))   # Output: 5.0 (Euclidean norm)


5.0


Limit values to a range
Useful to handle outliers or bounded probabilities.

In [9]:
arr = np.array([-10, 0.5, 1.2, 5])
print(np.clip(arr, 0, 1))  # Output: [0.  0.5 1.  1. ]


[0.  0.5 1.  1. ]


Covariance & Correlation

In [10]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])

print(np.cov(x, y))       # Covariance matrix
print(np.corrcoef(x, y))  # Correlation matrix


[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


 Shuffle your dataset
Used before train/test split to ensure randomness

In [11]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
np.random.shuffle(arr)
print(arr)


[[3 4]
 [1 2]
 [5 6]]


Matrix math
Used heavily in linear models, neural nets, etc.


In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))     # matrix multiplication
print(np.matmul(a, b))  # same thing


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


 Aggregate rows or columns

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr, axis=0))  # sum columns → [5 7 9]
print(np.sum(arr, axis=1))  # sum rows → [6 15]


[5 7 9]
[ 6 15]


Math functions
Used in loss functions, activations (like softmax), etc.

In [14]:
x = np.array([1, 2, 3])
print(np.exp(x))     # e^x
print(np.log(x))     # natural log
print(np.sqrt(x))    # square root
print(np.power(x, 2)) # square


[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[1.         1.41421356 1.73205081]
[1 4 9]


 Simulating ML data

In [15]:
X = np.random.randn(100, 5)  # 100 samples, 5 features
y = np.random.randint(0, 2, 100)  # binary labels
