# A file for functions  of numpy library


In [1]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# Create a 2D array
matrix = np.array([[1, 2], [3, 4]])
print(matrix)


[1 2 3 4]
[[1 2]
 [3 4]]


In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)        # element-wise addition
print(a * b)        # element-wise multiplication
print(a ** 2)       # element-wise square
print(b ** 3)       # element-wise cube

[5 7 9]
[ 4 10 18]
[1 4 9]
[ 64 125 216]


3.0
3.0
1.4142135623730951
15


In [6]:



print(np.mean(arr))   # average
print(np.median(arr))
print(np.std(arr))    # standard deviation
print(np.sum(arr))    # total sum


3.5
3.5
1.707825127659933
21


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)             # (2, 3)
print(arr.reshape(3, 2))     # reshape to (3, 2)
print(arr.flatten())         # convert to 1D: [1 2 3 4 5 6]



(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.vstack((a, b)))   # vertical stack (4 rows)
print(np.hstack((a, b)))   # horizontal stack (4 columns)
print(np.concatenate((a, b), axis=0))  # same as vstack


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

# Get all elements greater than 25
print(arr[arr > 25])

# Replace values
arr[arr > 25] = 99
print(arr)


[30 40 50]
[10 20 99 99 99]


In [ ]:
np.random.seed(42)                # reproducible results

print(np.random.rand(3))          # 3 random floats [0,1)
print(np.random.randint(0, 10, 5))  # 5 random integers [0,10)

# Random normal distribution
print(np.random.normal(loc=0, scale=1, size=(2, 3))) # loc = mean, scale = std dev, size = shape of matrix


[0.37454012 0.95071431 0.73199394]
[4 6 9 2 6]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


argmax gives the index of max value in array

argmin gives the index of min value in array

In [11]:
arr = np.array([10, 20, 5, 40])
print(np.argmax(arr))  # index of max → 3
print(np.argmin(arr))  # index of min → 2


3
2


basic dot product


In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))     # matrix multiplication
print(A @ B)            # same as dot product


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
